### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by tanelam** [softwaremom00/colmaracademy#5]
### Criteria 1: HTML Structure  
* _Score Level:_ 4
* _Comment(s):_ HTML implementation enables proper use of media queries, and its structure reflects the grouping and flow of content in the web browser.
 
### Criteria 2: Visual Layout for Both Desktop and Mobile Sizes
* _Score Level:_ 4
* _Comment(s):_  Desktop AND mobile layouts match the wireframe in all sections.Nice job with the visual layout of your site!
 
### Criteria 3: Responsive Design (Media Queries, Responsive Units, etc.)
* _Score Level:_ 4
* _Comment(s):_ Media queries kick in at appropriate breakpoints. Responsive units are used throughout.

### Criteria 4: Visual Design and Accessibility (Color Palette, Typography, Transitions, etc.)
* _Score Level:_ 4
* _Comment(s):_ Your CSS is nicely done - I really like the look and feel of your site.  An accessible color palette was chosen. Typographic considerations were made. CSS transitions were used.
 
### Overall Score: 16/16
**Overall, great job!** It is clear that you have been growing as a developer. Make sure to keep up the great work 👍 happy coding!

**Comment by softwaremom00** [comment]
Thank you so much.   I worked so hard on this project.   I did learn tons !
